
version: '3.8'

services:

    mysql:
        image: "mysql/mysql-server:8.0.21"
        container_name: mysql
        command: [ "mysqld",
                    "--character-set-server=utf8mb4",
                    "--collation-server=utf8mb4_unicode_ci",
                    "--bind-address=0.0.0.0",
                    "--log-error-verbosity",
                    "--require_secure_transport=ON",
                    "--ssl-ca=/etc/certs/root-ca.pem",
                    "--ssl-cert=/etc/certs/server-cert.pem",
                    "--ssl-key=/etc/certs/server-key.pem",
                    "--default_authentication_plugin=mysql_native_password" ]
        ports:
            - "3306:3306"
        networks:
            - wpnet
        volumes:
            - type: bind
              source: ./database
              target: /var/lib/mysql
            - type: bind
              source: ./certs
              target: /etc/certs/
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: "r00tr00t"
           # MYSQL_ROOT_HOST: "%"
           MYSQL_USER: wpuser
           MYSQL_PASSWORD: w0rdw0rd
           MYSQL_DATABASE: wpdb


networks:
    wpnet:
        driver: bridge
